sudo:
  required

services:
  - docker

before_install:
  - docker build -t ${DOCKER_ID}/ecommerceapp:client -f Dockerfile.dev .

script:
  - docker run -e CI=true ${DOCKER_ID}/ecommerceapp:client npm test -- --coverage

  